[package]
name = "rediSQL-rst"
version = "0.1.0"
authors = ["Simone Mosciatti <simone@redbeardlab.tech>"]
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = { git = "https://github.com/servo/rust-bindgen" }
gcc = "0.3.45"

[dependencies]
libc = "0.2.21"

